name: Deploy Portfolio

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Conecta no servidor e faz git pull
      - name: Deploy via git pull
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: u0_a253
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/portfolio
            git pull origin main
